# File: docker/docker-compose.yml
version: '3.8'

services:
  # PostgreSQL database for storing raw and aggregated launch data
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: spacex
      POSTGRES_PASSWORD: spacex
      POSTGRES_DB: launches
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spacex"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Trino query engine to access PostgreSQL data
  trino:
    image: trinodb/trino:latest
    ports:
      - "8080:8080"
    volumes:
      - ./trino/catalog:/etc/trino/catalog
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg_data:
